project-org = 'Level 12'
image-name = 'critic'

policy-arns = [
    'arn:aws:iam::089600762287:policy/CriticDDBAccessQA'
]

[deployed-env]
CRITIC_NAMESPACE = 'qa'

[event-rules.run-due-checks]
action='run_due_checks'
cron = '* * * * ? *'  # Every minute on the minute
